image: Visual Studio 2015

matrix:
  fast_finish: true

platform: Any CPU

configuration:
 - Debug
 - Release

build:
  verbosity: minimal

before_build:
#  - nuget restore

test_script:
 - ps: |
     $testResultsFile = ".\TestsResults.xml"
     $rest = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
     (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
     if ($rest.FailedCount -gt 0) {
         throw "$($res.FailedCount) tests failed."
     }